name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Generate the snake (output is saved in default path)
      - uses: Platane/snk@v3.2.0
        with:
          github_user_name: MasterFru

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .github/snake  # Ensure this matches the generated file's location
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
