name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:       # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: MasterFru
          outputs: dist/github-contribution-grid-snake.svg

      # Step 3: Deploy the generated file to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output  # Branch where the snake will be deployed
          build_dir: dist        # Directory containing the snake files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
